// <auto-generated />
namespace itproekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class postertomovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postertomovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202001280230561_postertomovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
